### ISSUE TITLE
Plugin is crashing homebridge

### ISSUE THREAD

**Issue by hoefs** [grzegorz914/homebridge-enphase-envoy#2]
```
[7/1/2020, 9:39:13 AM] [enphaseEnvoy] Device 192.168.2.25 Envoy-S, get device status data: { production: [Array], storage: [Array] }
[7/1/2020, 9:39:13 AM] [enphaseEnvoy] Device: 192.168.2.25 Envoy-S, state: Online.
[7/1/2020, 9:39:14 AM] [enphaseEnvoy] Device: 192.168.2.25 Envoy-S, requesting config information.
[7/1/2020, 9:39:14 AM] [enphaseEnvoy] {
  production: [
    {
      type: 'inverters',
      activeCount: 14,
      readingTime: 1593596328,
      wNow: 229,
      whLifetime: 2854782
    }
  ],
  storage: [
    {
      type: 'acb',
      activeCount: 0,
      readingTime: 0,
      wNow: 0,
      whNow: 0,
      state: 'idle'
    }
  ]
}
[7/1/2020, 9:39:14 AM] [enphaseEnvoy] Device: 192.168.2.25 Envoy-S, max power production: 0.716 kW
[7/1/2020, 9:39:14 AM] [enphaseEnvoy] Device: 192.168.2.25 Envoy-S, max power detected: Yes
[7/1/2020, 9:39:14 AM] TypeError: Cannot read property 'whToday' of undefined
    at envoyDevice.getDeviceState (/homebridge/node_modules/homebridge-enphase-envoy/index.js:207:61)
    at envoyDevice.getDeviceInfo (/homebridge/node_modules/homebridge-enphase-envoy/index.js:163:8)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
[7/1/2020, 9:39:14 AM] Got SIGTERM, shutting down Homebridge...
[7/1/2020, 9:39:14 AM] [enphaseEnvoy] Device: 192.168.2.25 Envoy-S, get Device info successful: {
  "envoy_info": {
    "time": [
      "1593596348"
    ],
    "device": [
      {
        "sn": [
          "121921106049"
        ],
        "pn": [
          "800-00553-r02"
        ],
        "software": [
          "R4.10.35"
        ],
        "euaid": [
          "4c8675"
        ],
        "seqnum": [
          "0"
        ],
        "apiver": [
          "1"
        ],
        "imeter": [
          "false"
        ]
      }
    ],
    "package": [
      {
        "$": {
          "name": "rootfs"
        },
        "pn": [
          "500-00001-r01"
        ],
        "version": [
          "02.00.00"
        ],
        "build": [
          "945"
        ]
      },
      {
        "$": {
          "name": "kernel"
        },
        "pn": [
          "500-00011-r01"
        ],
        "version": [
          "04.00.00"
        ],
        "build": [
          "5bb754"
        ]
      },
      {
        "$": {
          "name": "boot"
        },
        "pn": [
          "590-00018-r01"
        ],
        "version": [
          "02.00.01"
        ],
        "build": [
          "426697"
        ]
      },
      {
        "$": {
          "name": "app"
        },
        "pn": [
          "500-00002-r01"
        ],
        "version": [
          "04.10.35"
        ],
        "build": [
          "6ed292"
        ]
      },
      {
        "$": {
          "name": "devimg"
        },
        "pn": [
          "500-00005-r01"
        ],
        "version": [
          "01.02.186"
        ],
        "build": [
          "d0d70f"
        ]
      },
      {
        "$": {
          "name": "geo"
        },
        "pn": [
          "500-00008-r01"
        ],
        "version": [
          "02.01.22"
        ],
        "build": [
          "06e201"
        ]
      },
      {
        "$": {
          "name": "backbone"
        },
        "pn": [
          "500-00010-r01"
        ],
        "version": [
          "04.10.25"
        ],
        "build": [
          "7b7de5"
        ]
      },
      {
        "$": {
          "name": "meter"
        },
        "pn": [
          "500-00013-r01"
        ],
        "version": [
          "03.02.07"
        ],
        "build": [
          "4c9d48"
        ]
      },
      {
        "$": {
          "name": "agf"
        },
        "pn": [
          "500-00012-r01"
        ],
        "version": [
          "02.02.00"
        ],
        "build": [
          "c00a8f"
        ]
      },
      {
        "$": {
          "name": "security"
        },
        "pn": [
          "500-00016-r01"
        ],
        "version": [
          "02.00.00"
        ],
        "build": [
          "54a6dc"
        ]
      }
    ],
    "build_info": [
      {
        "build_time_gmt": [
          "1542157882"
        ],
        "build_id": [
          "release-4.10.x-103-Nov-12-18-18:25:06"
        ]
      }
    ]
  }
}
[7/1/2020, 9:39:14 AM] [enphaseEnvoy] -------- Envoy-S --------
[7/1/2020, 9:39:14 AM] [enphaseEnvoy] Manufacturer: Enphase
[7/1/2020, 9:39:14 AM] [enphaseEnvoy] Model: Envoy-S
[7/1/2020, 9:39:14 AM] [enphaseEnvoy] Serialnr: 121921106049
[7/1/2020, 9:39:14 AM] [enphaseEnvoy] Firmware: R4.10.35
[7/1/2020, 9:39:14 AM] [enphaseEnvoy] Inverters: 14
[7/1/2020, 9:39:14 AM] [enphaseEnvoy] ----------------------------------
```

Seems like it is detecting it, but is crashing after some seconds.

this seems to be working:
http://192.168.2.25/production.json
`{"production":[{"type":"inverters","activeCount":14,"readingTime":1593597231,"wNow":414,"whLifetime":2854865}],"storage":[{"type":"acb","activeCount":0,"readingTime":0,"wNow":0,"whNow":0,"state":"idle"}]}`

or
http://192.168.2.25/api/v1/production
```
{
  "wattHoursToday": 1654,
  "wattHoursSevenDays": 122504,
  "wattHoursLifetime": 2854864,
  "wattsNow": 414
}
```

**Comment by hoefs** [comment]
this seems to be working:
http://192.168.2.25/production.json
{"production":[{"type":"inverters","activeCount":14,"readingTime":1593594523,"wNow":812,"whLifetime":2854507}],"storage":[{"type":"acb","activeCount":0,"readingTime":0,"wNow":0,"whNow":0,"state":"idle"}]}

But I can't see a whToday...

**Comment by grzegorz914** [comment]
Ok, 
I see U do not use any meters, will be fixed in next update.

Thanks

**Comment by hoefs** [comment]
Can I add meters to my installation?
Seems like all the needed data is in the /api/production or am I wrong. Total for the day and the current wattage are there. A reason why the json is used and not the local api?

**Comment by grzegorz914** [comment]
If Your Envoy-S have inputs for Productions and Consumption CT then Yes.

**Comment by hoefs** [comment]
I have updated to latest. Homebridge is not crashing, but I cant add the accessory, it does not show up as before the update...

**Comment by hoefs** [comment]
Fixed with manually removing the 2 files in the persistent folder

**Comment by grzegorz914** [comment]
Change its name restart HB and add it again
