### ISSUE TITLE
TypeError: Cannot read property 'lastReportDate' of undefined

### ISSUE THREAD

**Issue by jcgillespie** [grzegorz914/homebridge-enphase-envoy#20]
Using plugin version 4.5.2

*Error*
```
[23/02/2021, 13:57:34] [enphaseEnvoy] Device: 192.168.9.10 Envoy, update Device state error: TypeError: Cannot read property 'lastReportDate' of undefined
    at envoyDevice.updateDeviceState (/usr/local/lib/node_modules/homebridge-enphase-envoy/index.js:2221:56)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by jcgillespie** [comment]
Update : using plugin version 4.5.4, the above error went away, but was replaced with this one.

```
Device: 192.168.9.10 Envoy, update Device state error: TypeError: Cannot read property 'push' of undefined
    at envoyDevice.updateDeviceState (/usr/local/lib/node_modules/homebridge-enphase-envoy/index.js:2503:40)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
