### ISSUE TITLE
update Device state error: TypeError: Cannot read property 'activeCount' of undefined

### ISSUE THREAD

**Issue by GentleJan** [grzegorz914/homebridge-enphase-envoy#22]
[2/25/2021, 1:19:30 PM] [enphaseEnvoy] Device: 192.168.178.11 Envoy, update Device state error: TypeError: Cannot read property 'activeCount' of undefined
    at envoyDevice.updateDeviceState (/homebridge/node_modules/homebridge-enphase-envoy/index.js:1536:69)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

Versie 4.6.5beta 5
envoy firmware: 5.0.55

**Comment by grzegorz914** [comment]
try beta .6

**Comment by GentleJan** [comment]
it works with beta 6
