### ISSUE TITLE
TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by GentleJan** [grzegorz914/homebridge-enphase-envoy#24]
[2/26/2021, 8:30:12 AM] [enphaseEnvoy] Device: 192.168.178.11 Envoy, update Device state error: TypeError: Cannot read property 'type' of undefined
    at envoyDevice.updateDeviceState (/homebridge/node_modules/homebridge-enphase-envoy/index.js:2028:64)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

Plugin Version 4.6.6
Homebridge 1.3.1
nodejs 14.16.0

**Comment by grzegorz914** [comment]
Can U get me output from 
http://envoy.local/production.json

**Comment by GentleJan** [comment]
{"production":[{"type":"inverters","activeCount":18,"readingTime":0,"wNow":0,"whLifetime":7905289}],"storage":[{"type":"acb","activeCount":0,"readingTime":0,"wNow":0,"whNow":0,"state":"idle"}]}

**Comment by grzegorz914** [comment]
Please also from
http://envoy.local/api/v1/production

**Comment by GentleJan** [comment]
{
  "wattHoursToday": 19393,
  "wattHoursSevenDays": 98401,
  "wattHoursLifetime": 7905289,
  "wattsNow": 0
}
