### ISSUE TITLE
issue with homebridge-enphase-envoy v4.7.8

### ISSUE THREAD

**Issue by hoefs** [grzegorz914/homebridge-enphase-envoy#29]
Same issue with homebridge-enphase-envoy v4.7.8
```
[3/10/2021, 5:35:21 PM] [enphaseEnvoy] Debug home: {
  software_build_epoch: 1542074240,
  is_nonvoy: false,
  db_size: '59 MB',
  db_percent_full: '16',
  timezone: 'Europe/Brussels',
  current_date: '03/10/2021',
  current_time: '17:35',
  network: [Object],
  tariff: 'none',
  comm: [Object],
  alerts: [],
  update_status: 'satisfied'
}, inventory: [ [Object], [Object], [Object] ], meters: [], production: {
  wattHoursToday: 6696,
  wattHoursSevenDays: 10477,
  wattHoursLifetime: 5145834,
  wattsNow: 43
}, productionCT: { production: [Array], storage: [Array] }
[3/10/2021, 5:35:24 PM] [enphaseEnvoy] Debug pcuCommCheck: {
  '121932043894': 4,
  '121932016547': 3,
  '121932034199': 3,
  '121932033746': 4,
  '121932016549': 3,
  '121932039512': 3,
  '121932038960': 3,
  '121932043380': 3,
  '121932039459': 4,
  '121910052727': 3,
  '121932039006': 4,
  '121931158966': 3,
  '121932035604': 3,
  '121931157713': 4,
  '121932039565': 3
}
[3/10/2021, 5:35:24 PM] [enphaseEnvoy] Debug production inverters: [
  [Object], [Object],
  [Object], [Object],
  [Object], [Object],
  [Object], [Object],
  [Object], [Object],
  [Object], [Object],
  [Object], [Object]
]
[3/10/2021, 5:35:24 PM] [enphaseEnvoy] Device: 192.168.2.25 Envoy-S, update Device state error: TypeError: Cannot read property 'type' of undefined
    at envoyDevice.updateDeviceState (/homebridge/node_modules/homebridge-enphase-envoy/index.js:2081:82)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
Had to downgrade to v4.7.6 again

**Comment by hoefs** [comment]
> sorry for that mistake, fixed in 4.7.9

Why aren't you working with a dev branch for the beta's? And only merging the finished versions to the master branch? The way you are working now, everybody sees the beta versions as an update in homebridge.
