### ISSUE TITLE
Cannot read property 'updateValue' of undefined

### ISSUE THREAD

**Issue by YouCanNotBeSerious** [grzegorz914/homebridge-enphase-envoy#33]
I have only found and tried this plugin today - i have this error.  What other info can i gather to help troubleshoot it?

```
**[04/07/2021, 08:38:01] [homebridge-enphase-envoy] Device: Envoy.local Envoy, update Device state error: TypeError: Cannot read property 'updateValue' of undefined
    at Service.enphaseEncharge.Service.updateCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:465:34)
    at envoyDevice.updateDeviceState (/usr/local/lib/node_modules/homebridge-enphase-envoy/index.js:2335:18)**
[04/07/2021, 08:38:48] [homebridge-enphase-envoy] Device: Envoy.local Envoy, requesting devices info.
[04/07/2021, 08:38:49] [homebridge-enphase-envoy] Device Envoy.local Envoy, debug infoData: <?xml version='1.0' encoding='UTF-8'?>
<envoy_info>
  <time>1625344729</time>
  <device>
    <sn>121548040020</sn>
    <pn>800-00552-r01</pn>
    <software>R5.0.54</software>
    <euaid>4c8675</euaid>
    <seqnum>0</seqnum>
    <apiver>1</apiver>
    <imeter>true</imeter>
  </device>
  <package name='rootfs'>
    <pn>500-00001-r01</pn>
    <version>02.00.00</version>
    <build>950</build>
  </package>
  <package name='kernel'>
    <pn>500-00011-r01</pn>
    <version>04.01.15</version>
    <build>8f3564</build>
  </package>
  <package name='boot'>
    <pn>590-00018-r01</pn>
    <version>02.00.01</version>
    <build>426697</build>
  </package>
  <package name='app'>
    <pn>500-00002-r01</pn>
    <version>05.00.54</version>
    <build>7c95f4</build>
  </package>
  <package name='devimg'>
    <pn>500-00005-r01</pn>
    <version>01.02.293</version>
    <build>6ceafd</build>
  </package>
  <package name='geo'>
    <pn>500-00008-r01</pn>
    <version>02.01.22</version>
    <build>2faa48</build>
  </package>
  <package name='backbone'>
    <pn>500-00010-r01</pn>
    <version>05.00.02</version>
    <build>4fe435</build>
  </package>
  <package name='meter'>
    <pn>500-00013-r01</pn>
    <version>03.02.07</version>
    <build>276642</build>
  </package>
  <package name='agf'>
    <pn>500-00012-r01</pn>
    <version>02.02.00</version>
    <build>fa5320</build>
  </package>
  <package name='security'>
    <pn>500-00016-r01</pn>
    <version>02.00.00</version>
    <build>54a6dc</build>
  </package>
  <package name='full'>
    <pn>500-00001-r01</pn>
    <version>02.00.00</version>
    <build>950</build>
  </package>
  <build_info>
    <build_id>release-5.0.x-104-Nov-23-20-10:04:21</build_id>
    <build_time_gmt>1606163182</build_time_gmt>
  </build_info>
</envoy_info>
, inventoryData: [ [Object], [Object], [Object] ], metersData: [ [Object], [Object] ]
[04/07/2021, 08:38:49] [homebridge-enphase-envoy] Device: Envoy.local Envoy, parse info.xml successful: {
  "envoy_info": {
    "time": [
      "1625344729"
    ],
    "device": [
      {
        "sn": [
          "121548040020"
        ],
        "pn": [
          "800-00552-r01"
        ],
        "software": [
          "R5.0.54"
        ],
        "euaid": [
          "4c8675"
        ],
        "seqnum": [
          "0"
        ],
        "apiver": [
          "1"
        ],
        "imeter": [
          "true"
        ]
      }
    ],
    "package": [
      {
        "$": {
          "name": "rootfs"
        },
        "pn": [
          "500-00001-r01"
        ],
        "version": [
          "02.00.00"
        ],
        "build": [
          "950"
        ]
      },
      {
        "$": {
          "name": "kernel"
        },
        "pn": [
          "500-00011-r01"
        ],
        "version": [
          "04.01.15"
        ],
        "build": [
          "8f3564"
        ]
      },
      {
        "$": {
          "name": "boot"
        },
        "pn": [
          "590-00018-r01"
        ],
        "version": [
          "02.00.01"
        ],
        "build": [
          "426697"
        ]
      },
      {
        "$": {
          "name": "app"
        },
        "pn": [
          "500-00002-r01"
        ],
        "version": [
          "05.00.54"
        ],
        "build": [
          "7c95f4"
        ]
      },
      {
        "$": {
          "name": "devimg"
        },
        "pn": [
          "500-00005-r01"
        ],
        "version": [
          "01.02.293"
        ],
        "build": [
          "6ceafd"
        ]
      },
      {
        "$": {
          "name": "geo"
        },
        "pn": [
          "500-00008-r01"
        ],
        "version": [
          "02.01.22"
        ],
        "build": [
          "2faa48"
        ]
      },
      {
        "$": {
          "name": "backbone"
        },
        "pn": [
          "500-00010-r01"
        ],
        "version": [
          "05.00.02"
        ],
        "build": [
          "4fe435"
        ]
      },
      {
        "$": {
          "name": "meter"
        },
        "pn": [
          "500-00013-r01"
        ],
        "version": [
          "03.02.07"
        ],
        "build": [
          "276642"
        ]
      },
      {
        "$": {
          "name": "agf"
        },
        "pn": [
          "500-00012-r01"
        ],
        "version": [
          "02.02.00"
        ],
        "build": [
          "fa5320"
        ]
      },
      {
        "$": {
          "name": "security"
        },
        "pn": [
          "500-00016-r01"
        ],
        "version": [
          "02.00.00"
        ],
        "build": [
          "54a6dc"
        ]
      },
      {
        "$": {
          "name": "full"
        },
        "pn": [
          "500-00001-r01"
        ],
        "version": [
          "02.00.00"
        ],
        "build": [
          "950"
        ]
      }
    ],
    "build_info": [
      {
        "build_id": [
          "release-5.0.x-104-Nov-23-20-10:04:21"
        ],
        "build_time_gmt": [
          "1606163182"
        ]
      }
    ]
  }
}
[04/07/2021, 08:38:49] [homebridge-enphase-envoy] Device: Envoy.local Envoy, saved Device Info successful.
[04/07/2021, 08:38:49] [homebridge-enphase-envoy] -------- Envoy --------
[04/07/2021, 08:38:49] [homebridge-enphase-envoy] Manufacturer: Enphase
[04/07/2021, 08:38:49] [homebridge-enphase-envoy] Model: Envoy
[04/07/2021, 08:38:49] [homebridge-enphase-envoy] Api ver: 1
[04/07/2021, 08:38:49] [homebridge-enphase-envoy] Firmware: R5.0.54
[04/07/2021, 08:38:49] [homebridge-enphase-envoy] SerialNr: 121548040020
[04/07/2021, 08:38:49] [homebridge-enphase-envoy] Time: 04/07/2021, 08:38:49
[04/07/2021, 08:38:49] [homebridge-enphase-envoy] ------------------------------
[04/07/2021, 08:38:49] [homebridge-enphase-envoy] Meters: Yes
[04/07/2021, 08:38:49] [homebridge-enphase-envoy] Production: Enabled
[04/07/2021, 08:38:49] [homebridge-enphase-envoy] Consumption: Enabled
[04/07/2021, 08:38:49] [homebridge-enphase-envoy] ------------------------------
[04/07/2021, 08:38:49] [homebridge-enphase-envoy] Q-Relays: 0
[04/07/2021, 08:38:49] [homebridge-enphase-envoy] Encharges: 7
[04/07/2021, 08:38:49] [homebridge-enphase-envoy] Inverters: 24
[04/07/2021, 08:38:49] [homebridge-enphase-envoy] ------------------------------
[04/07/2021, 08:38:49] [homebridge-enphase-envoy] Device: Envoy.local Envoy, requesting homeData and inventoryData.
[04/07/2021, 08:38:54] [homebridge-enphase-envoy] Device Envoy.local Envoy, debug homeData: {
  software_build_epoch: 1606149354,
  is_nonvoy: false,
  db_size: '31 MB',
  db_percent_full: '8',
  timezone: 'Pacific/Auckland',
  current_date: '07/04/2021',
  current_time: '08:38',
  network: [Object],
  tariff: 'time_of_use',
  comm: [Object],
  alerts: [],
  update_status: 'satisfied'
}, inventoryData: [ [Object], [Object], [Object] ]
[04/07/2021, 08:38:55] [homebridge-enphase-envoy] Debug productionData: {
  wattHoursToday: 14,
  wattHoursSevenDays: 75596,
  wattHoursLifetime: 36678938,
  wattsNow: 46
}, productionCtData: { production: [Array], consumption: [Array], storage: [Array] }, meterReadingData: [ [Object], [Object] ]
[04/07/2021, 08:38:55] [homebridge-enphase-envoy] Device: Envoy.local Envoy, savedProductionPowerMax: 0.065749 kW
[04/07/2021, 08:38:55] [homebridge-enphase-envoy] Device: Envoy.local Envoy, savedProductionPowerMax: 2.231176 kW
[04/07/2021, 08:38:55] [homebridge-enphase-envoy] Device: Envoy.local Envoy, savedProductionPowerMax: 2.231176 kW
[04/07/2021, 08:38:55] [homebridge-enphase-envoy] Device: Envoy.local Envoy, update Device state error: TypeError: Cannot read property 'updateValue' of undefined
    at Service.enphaseEncharge.Service.updateCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:465:34)
    at envoyDevice.updateDeviceState (/usr/local/lib/node_modules/homebridge-enphase-envoy/index.js:2335:18)
[04/07/2021, 08:39:48] [homebridge-enphase-envoy] Device: Envoy.local Envoy, requesting devices info.
[04/07/2021, 08:39:50] [homebridge-enphase-envoy] Device Envoy.local Envoy, debug infoData: <?xml version='1.0' encoding='UTF-8'?>
<envoy_info>
  <time>1625344789</time>
  <device>
    <sn>121548040020</sn>
    <pn>800-00552-r01</pn>
    <software>R5.0.54</software>
    <euaid>4c8675</euaid>
    <seqnum>0</seqnum>
    <apiver>1</apiver>
    <imeter>true</imeter>
  </device>
  <package name='rootfs'>
    <pn>500-00001-r01</pn>
    <version>02.00.00</version>
    <build>950</build>
  </package>
  <package name='kernel'>
    <pn>500-00011-r01</pn>
    <version>04.01.15</version>
    <build>8f3564</build>
  </package>
  <package name='boot'>
    <pn>590-00018-r01</pn>
    <version>02.00.01</version>
    <build>426697</build>
  </package>
  <package name='app'>
    <pn>500-00002-r01</pn>
    <version>05.00.54</version>
    <build>7c95f4</build>
  </package>
  <package name='devimg'>
    <pn>500-00005-r01</pn>
    <version>01.02.293</version>
    <build>6ceafd</build>
  </package>
  <package name='geo'>
    <pn>500-00008-r01</pn>
    <version>02.01.22</version>
    <build>2faa48</build>
  </package>
  <package name='backbone'>
    <pn>500-00010-r01</pn>
    <version>05.00.02</version>
    <build>4fe435</build>
  </package>
  <package name='meter'>
    <pn>500-00013-r01</pn>
    <version>03.02.07</version>
    <build>276642</build>
  </package>
  <package name='agf'>
    <pn>500-00012-r01</pn>
    <version>02.02.00</version>
    <build>fa5320</build>
  </package>
  <package name='security'>
    <pn>500-00016-r01</pn>
    <version>02.00.00</version>
    <build>54a6dc</build>
  </package>
  <package name='full'>
    <pn>500-00001-r01</pn>
    <version>02.00.00</version>
    <build>950</build>
  </package>
  <build_info>
    <build_id>release-5.0.x-104-Nov-23-20-10:04:21</build_id>
    <build_time_gmt>1606163182</build_time_gmt>
  </build_info>
</envoy_info>
, inventoryData: [ [Object], [Object], [Object] ], metersData: [ [Object], [Object] ]
[04/07/2021, 08:39:50] [homebridge-enphase-envoy] Device: Envoy.local Envoy, parse info.xml successful: {
  "envoy_info": {
    "time": [
      "1625344789"
    ],
    "device": [
      {
        "sn": [
          "121548040020"
        ],
        "pn": [
          "800-00552-r01"
        ],
        "software": [
          "R5.0.54"
        ],
        "euaid": [
          "4c8675"
        ],
        "seqnum": [
          "0"
        ],
        "apiver": [
          "1"
        ],
        "imeter": [
          "true"
        ]
      }
    ],
    "package": [
      {
        "$": {
          "name": "rootfs"
        },
        "pn": [
          "500-00001-r01"
        ],
        "version": [
          "02.00.00"
        ],
        "build": [
          "950"
        ]
      },
      {
        "$": {
          "name": "kernel"
        },
        "pn": [
          "500-00011-r01"
        ],
        "version": [
          "04.01.15"
        ],
        "build": [
          "8f3564"
        ]
      },
      {
        "$": {
          "name": "boot"
        },
        "pn": [
          "590-00018-r01"
        ],
        "version": [
          "02.00.01"
        ],
        "build": [
          "426697"
        ]
      },
      {
        "$": {
          "name": "app"
        },
        "pn": [
          "500-00002-r01"
        ],
        "version": [
          "05.00.54"
        ],
        "build": [
          "7c95f4"
        ]
      },
      {
        "$": {
          "name": "devimg"
        },
        "pn": [
          "500-00005-r01"
        ],
        "version": [
          "01.02.293"
        ],
        "build": [
          "6ceafd"
        ]
      },
      {
        "$": {
          "name": "geo"
        },
        "pn": [
          "500-00008-r01"
        ],
        "version": [
          "02.01.22"
        ],
        "build": [
          "2faa48"
        ]
      },
      {
        "$": {
          "name": "backbone"
        },
        "pn": [
          "500-00010-r01"
        ],
        "version": [
          "05.00.02"
        ],
        "build": [
          "4fe435"
        ]
      },
      {
        "$": {
          "name": "meter"
        },
        "pn": [
          "500-00013-r01"
        ],
        "version": [
          "03.02.07"
        ],
        "build": [
          "276642"
        ]
      },
      {
        "$": {
          "name": "agf"
        },
        "pn": [
          "500-00012-r01"
        ],
        "version": [
          "02.02.00"
        ],
        "build": [
          "fa5320"
        ]
      },
      {
        "$": {
          "name": "security"
        },
        "pn": [
          "500-00016-r01"
        ],
        "version": [
          "02.00.00"
        ],
        "build": [
          "54a6dc"
        ]
      },
      {
        "$": {
          "name": "full"
        },
        "pn": [
          "500-00001-r01"
        ],
        "version": [
          "02.00.00"
        ],
        "build": [
          "950"
        ]
      }
    ],
    "build_info": [
      {
        "build_id": [
          "release-5.0.x-104-Nov-23-20-10:04:21"
        ],
        "build_time_gmt": [
          "1606163182"
        ]
      }
    ]
  }
}
[04/07/2021, 08:39:50] [homebridge-enphase-envoy] Device: Envoy.local Envoy, saved Device Info successful.
[04/07/2021, 08:39:50] [homebridge-enphase-envoy] -------- Envoy --------
[04/07/2021, 08:39:50] [homebridge-enphase-envoy] Manufacturer: Enphase
[04/07/2021, 08:39:50] [homebridge-enphase-envoy] Model: Envoy
[04/07/2021, 08:39:50] [homebridge-enphase-envoy] Api ver: 1
[04/07/2021, 08:39:50] [homebridge-enphase-envoy] Firmware: R5.0.54
[04/07/2021, 08:39:50] [homebridge-enphase-envoy] SerialNr: 121548040020
[04/07/2021, 08:39:50] [homebridge-enphase-envoy] Time: 04/07/2021, 08:39:49
[04/07/2021, 08:39:50] [homebridge-enphase-envoy] ------------------------------
[04/07/2021, 08:39:50] [homebridge-enphase-envoy] Meters: Yes
[04/07/2021, 08:39:50] [homebridge-enphase-envoy] Production: Enabled
[04/07/2021, 08:39:50] [homebridge-enphase-envoy] Consumption: Enabled
[04/07/2021, 08:39:50] [homebridge-enphase-envoy] ------------------------------
[04/07/2021, 08:39:50] [homebridge-enphase-envoy] Q-Relays: 0
[04/07/2021, 08:39:50] [homebridge-enphase-envoy] Encharges: 7
[04/07/2021, 08:39:50] [homebridge-enphase-envoy] Inverters: 24
[04/07/2021, 08:39:50] [homebridge-enphase-envoy] ------------------------------
[04/07/2021, 08:39:50] [homebridge-enphase-envoy] Device: Envoy.local Envoy, requesting homeData and inventoryData.
[04/07/2021, 08:39:54] [homebridge-enphase-envoy] Device Envoy.local Envoy, debug homeData: {
  software_build_epoch: 1606149354,
  is_nonvoy: false,
  db_size: '31 MB',
  db_percent_full: '8',
  timezone: 'Pacific/Auckland',
  current_date: '07/04/2021',
  current_time: '08:39',
  network: [Object],
  tariff: 'time_of_use',
  comm: [Object],
  alerts: [],
  update_status: 'satisfied'
}, inventoryData: [ [Object], [Object], [Object] ]
[04/07/2021, 08:39:55] [homebridge-enphase-envoy] Debug productionData: {
  wattHoursToday: 14,
  wattHoursSevenDays: 75596,
  wattHoursLifetime: 36678938,
  wattsNow: 46
}, productionCtData: { production: [Array], consumption: [Array], storage: [Array] }, meterReadingData: [ [Object], [Object] ]
[04/07/2021, 08:39:55] [homebridge-enphase-envoy] Device: Envoy.local Envoy, savedProductionPowerMax: 0.065749 kW
[04/07/2021, 08:39:55] [homebridge-enphase-envoy] Device: Envoy.local Envoy, productionPowerMaxFile saved successful in: /var/lib/homebridge/enphaseEnvoy/productionPowerMax_Envoylocal 0.069802 kW
[04/07/2021, 08:39:55] [homebridge-enphase-envoy] Device: Envoy.local Envoy, savedProductionPowerMax: 2.231176 kW
[04/07/2021, 08:39:55] [homebridge-enphase-envoy] Device: Envoy.local Envoy, savedProductionPowerMax: 2.231176 kW
[04/07/2021, 08:39:55] [homebridge-enphase-envoy] Device: Envoy.local Envoy, update Device state error: TypeError: Cannot read property 'updateValue' of undefined
    at Service.enphaseEncharge.Service.updateCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:465:34)
    at envoyDevice.updateDeviceState (/usr/local/lib/node_modules/homebridge-enphase-envoy/index.js:2335:18)

```

**Comment by YouCanNotBeSerious** [comment]
Maybe this is the relevant part - something about battery SoC?
```

[04/07/2021, 09:08:52] [homebridge-enphase-envoy] This plugin threw an error from the characteristic 'Percent full': Unhandled error thrown inside read handler for characteristic: Cannot read property '6' of undefined. See https://git.io/JtMGR for more info.
[04/07/2021, 09:08:52] [homebridge-enphase-envoy] TypeError: Cannot read property '6' of undefined
    at Characteristic.enphaseEnchargePercentFull.getHandler (/usr/local/lib/node_modules/homebridge-enphase-envoy/index.js:3309:53)
    at Characteristic.enphaseEnchargePercentFull.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1450:32)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at Characteristic.enphaseEnchargePercentFull.Characteristic.handleGetRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:656:24)
    at Characteristic.enphaseEnchargePercentFull.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2103:22)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
```

**Comment by YouCanNotBeSerious** [comment]
Hi - i updated to fix #33, now the error is:

[05/07/2021, 10:03:17] [homebridge-enphase-envoy] This plugin generated a warning from the characteristic 'Percent full': characteristic value expected valid finite number and received "58,58,57,55,55,56,60" (object). See https://git.io/JtMGR for more info.
[05/07/2021, 10:03:17] [homebridge-enphase-envoy] Error: 
    at Characteristic.enphaseEnchargePercentFull.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at Characteristic.enphaseEnchargePercentFull.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1931:16)
    at Characteristic.enphaseEnchargePercentFull.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1456:24)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by grzegorz914** [comment]
Ok, I have finally fixed this but right now have no possibility publish it to npm (I’m on holidays)

**Comment by YouCanNotBeSerious** [comment]
Hey man I get a free and very excellent plugin, I have no right to say anything other than thank you, and i look forward to it when you get around to publishing :-)

**Comment by grzegorz914** [comment]
Try update and let me know

**Comment by YouCanNotBeSerious** [comment]
Seems fine now, no errors in log, values in app are correct.....thanks!
