### ISSUE TITLE
Homebrdige crashing with v3.5.63

### ISSUE THREAD

**Issue by hoefs** [grzegorz914/homebridge-enphase-envoy#5]
Hi,

Just updated to latest version. Now homebridge is crashing:

```
[1/29/2021, 2:58:40 PM] ReferenceError: me is not defined
    at new envoyDevice (/homebridge/node_modules/homebridge-enphase-envoy/index.js:274:47)
    at HomebridgeAPI.<anonymous> (/homebridge/node_modules/homebridge-enphase-envoy/index.js:195:11)
    at HomebridgeAPI.emit (events.js:327:22)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/homebridge/src/api.ts:251:10)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:158:14)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
[1/29/2021, 2:58:40 PM] Got SIGTERM, shutting down Homebridge...
[1/29/2021, 2:58:40 PM] ERR_SERVER_CLOSED: Cannot send packets on a closed mdns server!
    at MDNSServer.assertBeforeSend (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/MDNSServer.ts:403:13)
    at MDNSServer.sendOnAllNetworksForService (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/MDNSServer.ts:302:10)
    at MDNSServer.sendQueryBroadcast (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/MDNSServer.ts:263:26)
    at Prober.sendProbeRequest (/usr/local/lib/node_modules/homebridge/node_modules/@homebridge/ciao/src/responder/Prober.ts:165:17)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

removed config and homebridge is working again:
 ```
       {
            "devices": [
                {
                    "name": "Envoy-S",
                    "host": "192.168.2.25",
                    "refreshInterval": 30,
                    "envoyUser": "envoy",
                    "envoyPasswd": "XXX",
                    "installerUser": "installer",
                    "installerPasswd": "XXX",
                    "enchargeStorageOffset": 0,
                    "powerProductionMaxDetected": 3400,
                    "energyProductionLifetimeOffset": 0,
                    "powerConsumptionTotalMaxDetected": 0,
                    "energyConsumptionTotalLifetimeOffset": 0,
                    "powerConsumptionNetMaxDetected": 0,
                    "energyConsumptionNetLifetimeOffset": 0,
                    "manufacturer": "Enphase",
                    "modelName": "Envoy-S",
                    "serialNumber": "XXX",
                    "firmwareRevision": "R4.10.35"
                }
            ],
            "platform": "enphaseEnvoy"
        }
```

**Comment by hoefs** [comment]
Now it is starting but with address collision:
```
1/29/2021, 3:33:07 PM] [enphaseEnvoy] Device: 192.168.2.25 Envoy-S, last inverter: undefined power: NaN W
[1/29/2021, 3:33:07 PM] [enphaseEnvoy] Device: 192.168.2.25 Envoy-S, max inverter: undefined power: NaN W
[1/29/2021, 3:33:07 PM] [enphaseEnvoy] prepareAccessory
[1/29/2021, 3:33:07 PM] [enphaseEnvoy] prepareInformationService
[1/29/2021, 3:33:07 PM] [enphaseEnvoy] prepareEnvoyService
[1/29/2021, 3:33:07 PM] [enphaseEnvoy] Device: 192.168.2.25 Envoy-S, publishExternalAccessories.
[1/29/2021, 3:33:07 PM] [enphaseEnvoy] Device: 192.168.2.25 Envoy-S, update Device state error: Error: Accessory Envoy-S experienced an address collision.
    at /usr/local/lib/node_modules/homebridge/src/server.ts:581:15
    at Array.forEach (<anonymous>)
    at Server.handlePublishExternalAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:561:17)
    at HomebridgeAPI.emit (events.js:315:20)
    at HomebridgeAPI.publishExternalAccessories (/usr/local/lib/node_modules/homebridge/src/api.ts:302:10)
    at envoyDevice.prepareAccessory (/homebridge/node_modules/homebridge-enphase-envoy/index.js:328:14)
    at envoyDevice.updateDeviceState (/homebridge/node_modules/homebridge-enphase-envoy/index.js:949:10)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5), state: Offline
```

**Comment by hoefs** [comment]
Last update _homebridge-enphase-envoy v3.5.75_ seems to fix that issue...

What is this inverter thing?
```
[1/29/2021, 3:34:43 PM] [enphaseEnvoy] Device 192.168.2.25 Envoy-S, get device status data: {
  wattHoursToday: 2511,
  wattHoursSevenDays: 26004,
  wattHoursLifetime: 4781330,
  wattsNow: 179
}, data1 { production: [Array], storage: [Array] }
[1/29/2021, 3:34:43 PM] [enphaseEnvoy] Device: 192.168.2.25 Envoy-S, power production: 0.179 kW
[1/29/2021, 3:34:43 PM] [enphaseEnvoy] Device: 192.168.2.25 Envoy-S, power production max: 3.421 kW
[1/29/2021, 3:34:43 PM] [enphaseEnvoy] Device: 192.168.2.25 Envoy-S, power production max detected: No
[1/29/2021, 3:34:43 PM] [enphaseEnvoy] Device: 192.168.2.25 Envoy-S, energy production Today: 2.511 kWh
[1/29/2021, 3:34:43 PM] [enphaseEnvoy] Device: 192.168.2.25 Envoy-S, energy production last 7 Days: 26.004 kWh
[1/29/2021, 3:34:43 PM] [enphaseEnvoy] Device: 192.168.2.25 Envoy-S, energy production Lifetime: 4781.33 kWh
[1/29/2021, 3:34:46 PM] [enphaseEnvoy] Device: 192.168.2.25 Envoy-S, last inverter: undefined power: NaN W
[1/29/2021, 3:34:46 PM] [enphaseEnvoy] Device: 192.168.2.25 Envoy-S, max inverter: undefined power: NaN W
```

**Comment by hoefs** [comment]
homebridge-enphase-envoy v3.5.77 (fast updates...)

This drops a lot of html code in de homebridge logs...

```
[1/29/2021, 3:48:07 PM] [enphaseEnvoy] Device 192.168.2.25 Envoy-S, get device status data: {
  wattHoursToday: 2545,
  wattHoursSevenDays: 25877,
  wattHoursLifetime: 4781364,
  wattsNow: 112
}, data1 { production: [Array], storage: [Array] }
[1/29/2021, 3:48:07 PM] [enphaseEnvoy] Device: 192.168.2.25 Envoy-S, power production: 0.112 kW
[1/29/2021, 3:48:07 PM] [enphaseEnvoy] Device: 192.168.2.25 Envoy-S, power production max: 3.421 kW
[1/29/2021, 3:48:07 PM] [enphaseEnvoy] Device: 192.168.2.25 Envoy-S, power production max detected: No
[1/29/2021, 3:48:07 PM] [enphaseEnvoy] Device: 192.168.2.25 Envoy-S, energy production Today: 2.545 kWh
[1/29/2021, 3:48:07 PM] [enphaseEnvoy] Device: 192.168.2.25 Envoy-S, energy production last 7 Days: 25.877 kWh
[1/29/2021, 3:48:07 PM] [enphaseEnvoy] Device: 192.168.2.25 Envoy-S, energy production Lifetime: 4781.364 kWh
[1/29/2021, 3:48:09 PM] [enphaseEnvoy]       <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN">
      <html lang="en">
      <!-- START HEAD CONTENT -->
      <head>
        <title>error</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <link rel="icon"
              type="image/png" href="/images/favicon.ico?v=6">
        <!-- include style sheet -->
        <link rel="styleSheet" type="text/css" href="/include/css/style.css" >
        <style type="text/css">.nav { width: 190px; font-size: 10px; padding: 10px; margin: 10px;float: left; background: #D8DBD4; color: #213d30; border: 2px solid #333; }
        .navholder { width: auto; height: auto; float: left; margin: 10px 0px 0 0 }
        .tbl_cap { font-size:8pt; background-color:#DD4F05; color:white; border-style:solid; border-width:1px; border-color:white; }
        .tbl_bod { font-family:arial; font-size:8pt; color:#213d30; background-color:#D8DBD4; border-style:solid; border-color:white; border-width:1px; }
        .tbl_bod_right { font-family:arial; font-size:8pt; color:#213d30; background-color:#D8DBD4; border-style:solid; border-color:white; border-width:1px; text-align:right }
        .tbl_hdr { font-size:8pt; background-color:#CCCCCC; border-style:solid; border-width:1px; border-color:white; color:#213d30; }
        .clearer { clear: both; font-size: 1px; }
        .outer { width: auto; height: auto; padding: 0px; font-size: 10px }
        .table1 { width: 100%; margin-left: auto; margin-right: auto;border: 1px solid #CCCCCC }
        .table2 { width: 100%;text-align: center;margin-left: auto; margin-right: auto;border: 1px solid #CCCCCC }
        .table3 { width: 720px;margin-left: auto; margin-right: auto;border: 1px solid #CCCCCC }
        .div_params { height: 190px; width: 380px; overflow: auto;margin-left: auto; margin-right: auto; }
        .div_edit_params { height: 230px; width: 470px; overflow: auto;margin-left: auto; margin-right: auto; }
        .div_outer_box { width: 720px;margin-left: auto; margin-right: auto;border: 1px solid #FFFFFF }
        .txt_expl_center { font-size: 12px; text-align:center;height: auto; border: 1px solid #CCCCCC;margin-top: 5px; margin-left: 5px; margin-right: auto; }
        .label_text_right { text-align: right; border: 1px solid #CCCCCC;font-size: 10px; }
        .label_text_left { text-align: left; border: 1px solid #CCCCCC;font-size: 10px; }
        .label_text_left_alert { text-align: left; color: #7d3020; border: 1px solid #CCCCCC;font-size: 12px; }
        .link_cell_right { font-size: 10px;height: auto; border: 1px solid #CCCCCC;text-align: right;margin-top: 5px; margin-left: auto; margin-right: 25px; }
        .link_cell_left { font-size: 10px;height: auto; border: 1px solid #CCCCCC;text-align: left;margin-top: 5px; margin-left: 25px; margin-right: auto; }
        .link_cell_right_out { font-size: 12px; padding: 15px;height: auto; border: 1px solid #CCCCCC;text-align: right;margin-top: 5px; margin-left: auto; margin-right: 25px; }
        .link_cell_left_out { font-size: 12px;height: auto; border: 1px solid #CCCCCC;text-align: left; padding: 15px;margin-top: 5px; margin-left: 25px; margin-right: auto; }
        .ns_fldset { height: auto; width: 720px; border: 1px solid #7d3020; background: #CCCCCC; padding: 15px; }
        .ns_fldset_inner { border: 1px solid #7d3020; background: #CCCCCC; }
        .enp_legend { text-align: left; border: 1px solid #7d3020; background: #FFD401; }
        .input_left { border: 1px solid #CCCCCC; text-align: left; }
        .grid_config { float: left; margin-left: 50px; width: 830px; text-align: center; }
        .swimgnav { width: 160px; height: auto; font-size: 10px; padding: 10px; margin: 10px;float: left; background: #D8DBD4; color: #213d30;border: 2px solid #333; }
        .frames { clear: right; width: auto; padding: 15px; height: auto; margin-left: 200px; margin-right: auto; }
        .tbl_cap_left { font-size:8pt; background-color:#DD4F05; color:white; border-style:solid; border-width:1px; border-color:white; text-align:left; }
        .tbl_cap_center { font-size:8pt; background-color:#DD4F05; color:white; border-style:solid; border-width:1px; border-color:white; text-align:center; }
        .tbl_bod_left { font-family:arial; font-size:8pt; color:#213d30; background-color:#D8DBD4; border-style:solid; border-color:white; border-width:1px; text-align:left; }
        .tablePaged { float: left;width: 100%;text-align: center;margin-left: auto; margin-right: auto;border: 1px solid #CCCCCC }
        .table.dataTable { margin: 0 auto; clear: both; width: 100%; }
        .table.dataTable thead th { padding: 3px 18px 3px 10px;border-bottom: 1px solid black;font-weight: bold;cursor: pointer;*cursor: hand; }
        .table.dataTable tfoot th { padding: 3px 18px 3px 10px;border-top: 1px solid black;font-weight: bold; }
        .table.dataTable td { padding: 3px 10px; }
        .table.dataTable td.center, table.dataTable td.dataTables_empty { text-align: center; }
        .table.dataTable tr.odd { background-color: #E2E4FF; }
        .table.dataTable tr.even { background-color: white; }
        .table.dataTable tr.odd td.sorting_1 { background-color: #D3D6FF; }
        .table.dataTable tr.odd td.sorting_2 { background-color: #DADCFF; }
        .table.dataTable tr.odd td.sorting_3 { background-color: #E0E2FF; }
        .table.dataTable tr.even td.sorting_1 { background-color: #EAEBFF; }
        .table.dataTable tr.even td.sorting_2 { background-color: #F2F3FF; }
        .table.dataTable tr.even td.sorting_3 { background-color: #F9F9FF; }
        .dataTables_wrapper { position: relative; clear: both; *zoom: 1; }
        .dataTables_length { float: left; }
        .dataTables_filter { margin: 0px 0px 2px 0px; float: right; text-align: right; }
        .DTTT_button_text { margin: 0px 0px 0px 3px; float: right; text-align: right; }
        .dataTables_info { clear: both; float: left; }
        .dataTables_paginate { float: right; text-align: right; }
        .paging_full_numbers { height: 22px; line-height: 22px; }
        .paging_full_numbers a:active { outline: none }
        .paging_full_numbers a:hover { text-decoration: none; }
        .paging_full_numbers a.paginate_button,.paging_full_numbers a.paginate_active { border: 1px solid #aaa;-webkit-border-radius: 5px;-moz-border-radius: 5px;border-radius: 5px;padding: 2px 5px;margin: 0 3px;cursor: pointer;*cursor: hand;color: #333 !important; }
        .paging_full_numbers a.paginate_button { background-color: #ddd; }
        .paging_full_numbers a.paginate_button:hover { background-color: #ccc;text-decoration: none !important; }
        .paging_full_numbers a.paginate_active { background-color: #99B3FF; }
        .paging_full_numbers a.paginate_button_disabled { border: 1px solid #aaa;-webkit-border-radius: 5px;-moz-border-radius: 5px;border-radius: 5px;padding: 2px 5px;margin: 0 3px;cursor: default;opacity: 0.6;color: gray; }
        .dataTables_processing { position: absolute;top: 50%;left: 50%;width: 250px;height: 30px;margin-left: -125px;margin-top: -15px;padding: 14px 0 2px 0;border: 1px solid #ddd;text-align: center;color: #999;font-size: 14px;background-color: white; }
        .sorting { padding: 2px 15px;background-clip: padding-box;background-origin: border-box;background-image: url('/images/sort_both.png');background-repeat: no-repeat;background-position: right center;background-color: #DD4F05; }
        .sorting_asc { padding: 2px 15px;background-clip: padding-box;background-origin: border-box;background-image: url('/images/sort_asc.png');background-repeat: no-repeat;background-position: right center;background-color: #DD4F05; }
        .sorting_desc { padding: 2px 15px;background-clip: padding-box;background-origin: border-box;background-image: url('/images/sort_desc.png');background-repeat: no-repeat;background-position: right center;background-color: #DD4F05; }
        .sorting_asc_disabled { padding: 2px 15px;background-clip: padding-box;background-origin: border-box;background-image: url('/images/sort_asc_disabled.png');background-repeat: no-repeat;background-position: right center;background-color: #DD4F05; }
        .sorting_desc_disabled { padding: 2px 15px;background-clip: padding-box;background-origin: border-box;background-image: url('/images/sort_desc_disabled.png');background-repeat: no-repeat;background-position: right center;background-color: #DD4F05; }
        .table.dataTable th:active { outline: none; }
        .p.t_fixed_header_scroll_inner { width: 100%;height: 200px; }
        .div.t_fixed_header_scroll_outer { top: 0; left: 0; visibility: hidden; width: 200px; height: 150px; overflow: hidden; }
        .div.t_fixed_header { position: relative;margin: 0;width: 100%; }
        .div.t_fixed_header * { margin: 0;padding: 0; }
        .div.t_fixed_header table.head { position: relative; }
        .div.t_fixed_header table { width: 100%;table-layout: fixed;empty-cells: show;border-collapse: collapse;border-spacing: 0; }
        .div.t_fixed_header table.headtable td.fillScrollbar { font-size: 0px;-o-text-overflow: inherit;text-overflow: inherit; }
        .div.t_fixed_header tr th, div.t_fixed_header tr td { overflow: hidden;white-space: nowrap;-o-text-overflow: ellipsis;text-overflow: ellipsis; }
        .div.t_fixed_header.t_fixed_header_wrap tr th, div.t_fixed_header.t_fixed_header_wrap tr td { white-space: normal; }
        .div.t_fixed_header div.body { overflow-x: auto;padding: 0;width: 100%; }
        .div.t_fixed_header_main_wrapper { position: relative;overflow: hidden; }
        .div.t_fixed_header_main_wrapper_child { position: relative;width: 100% }
        .div.t_fixed_header_main_wrapper.ui { border-width: 1px 1px 1px 1px;border-style: solid;font-weight: normal;font-size: 1.1em; }
        .div.t_fixed_header_main_wrapper.ui  div.t_fixed_header_caption { text-align: center;font-weight: bold;padding: 0 5px;height: 30px;line-height: 30px;border-width: 0 0 1px 0;border-style: solid; }
        .div.t_fixed_header_main_wrapper.ui  div.t_fixed_header_caption.toggle { border-width: 0; }
        .div.t_fixed_header div.headtable { border: 0;overflow-x: hidden;overflow-y: auto; }
        .div.t_fixed_header.ui .body { border-width: 1px 0 0 0;border-style: solid;background-image: none; }
        .div.t_fixed_header.ui .headtable th { padding: 5px;text-align: center;border-width: 0 1px 0 0;border-style: solid; }
        .div.t_fixed_header.ui .headtable .hover { cursor: pointer;height: 16px; }
        .div.t_fixed_header.ui .headtable th span.ui-resize { background: transparent;cursor: col-resize;display: inline;float: right;height: 20px;margin: -3px -5px -5px 0;width: 5px;z-index: 10000; }
        .div.t_fixed_header.ui div.ui-resize-ghost { display: none;position: absolute;top: 0;width: 2px;border: none; }
        .div.t_fixed_header.ui .body tr { border: 0px; }
        .div.t_fixed_header.ui .body td { padding: 5px;text-align: left;line-height: 15px; }
        .div.t_fixed_header.ui .body tr td { border-width: 0 1px 1px 0;border-style: solid;background: none; }
        .div.t_fixed_header.ui .body tr:last-child td { border-bottom-width: 0px; }
        .div.t_fixed_header.ui.default .headtable th:last-child, div.t_fixed_header.ui.default .body td:last-child { border-right-width: 0px; }
        .div.t_fixed_header.ui .body td.last_td, div.t_fixed_header.ui .headtable th.last_td { border-right-width: 0px; }
        .div.t_fixed_header_main_wrapper.ui div.pager { border-width: 0 0 0 0;padding: 4px 2px 2px 3px;overflow: hidden;background-image: none; }
        .div.t_fixed_header_main_wrapper.ui div.pager .button { float: right;padding: 4px 0;cursor: pointer; }
        .div.t_fixed_header_main_wrapper.ui div.pager .button.noborder { border-right-width : 0px; }
        .div.t_fixed_header_main_wrapper.ui div.pager .button span { margin: 0 4px; }
        .div.t_fixed_header_main_wrapper.ui div.pager div.page_infos { height: 27px;line-height: 27px;float: right;margin-right: 10px;font-weight: normal; }
        </style>
        <!-- include JS libraries -->
        <script type="text/JavaScript">
        <!--
        function refreshPage(period) {
          setTimeout("document.forms['tpm_status'].submit()", period);
        }
        //   -->
        </script>
        
      </head>
      <!-- END HEAD CONTENT -->
        <body>
      <!-- START TOP NAV CONTENT -->
        <form action="/error" method="post">
        <div class="nav_header">
        <input type="hidden" name="fname" value="nav_header" >
        <input type="hidden" name="profile" value="0" >
        <input type="hidden" name="regSpec" value="0" >
        <input type="hidden" name="country" value="0" >
        <input type="hidden" name="regSpecName" value="" >
        <input type="hidden" name="profileName" value="" >
        <table width="100%" style="border-style:none;">
          <tr>
            <td class="hdr_line" valign="middle">
                <a href="http://enphase.com/en/" title="Visit the Enphase Energy website">
                <img src="/images/enphase-logo.png"
                style="background:white; text-align:left; height:50px;"
                alt="Enphase Energy, Inc.">
                </a>
                </td>
            <td class="hdr_line" valign="middle" colspan="4">Envoy Serial Number: 121921106049</td>
            <td class="hdr_line" valign="middle">
                <a href="http://enlighten.enphaseenergy.com?locale=en" title="Visit the Enlighten website">
                <img src="/images/enlighten_logo.png"
                style="background:white; text-align:right; height:40px;"
                alt="Enlighten website">
                </a>
                </td>
          </tr>
          <tr>
            <td class="hdr_line"><a href="/home?locale=en&classic=1">Home</a></td>
            <td class="hdr_line"><a href="/event?locale=en">Events</a></td>
            <td class="hdr_line"><a id="nav_header_production" href="/production?locale=en">Production</a></td>             
            <td class="hdr_line"><a id="nav_header_inventory" href="/inventory?locale=en">Inventory</a></td>
            <td class="hdr_line"><a id="nav_header_admin" href="/admin/home?locale=en">Administration</a></td>
            <td class="hdr_line"></td>
            <td class="hdr_line" align="left">Language
              <select autocomplete="off" id="locale" name="locale" onchange="this.form.submit()">                 ["<option value=nl>Nederlands</option>", "<option value=fr>Français</option>", "<option value=de>Deutsch</option>", "<option value=it>Italiano</option>", "<option value=es>Español</option>", "<option value=en selected=\"selected\" >English</option>"]
              </select>
            </td>
          </tr>
        </table>
        </div>
        </form>
        <HR>
      <!-- END TOP NAV CONTENT -->
      <!-- START MAIN PAGE CONTENT -->
    <!DOCTYPE html PUBLIC "-//IETF//DTD HTML 2.0//EN">
    <html>
    <!-- START HEAD CONTENT -->
    <head>
      <!-- include style sheet -->
      <link rel="StyleSheet" type="text/css" href="/include/css/style.css" />
      <!-- include JS libraries -->
    </head>
    <!-- END HEAD CONTENT -->
    <body>
    <center>
    <img src="/images/emu-small.gif" style="margin:10px" alt="Emu"/>
    <h2>Page Not Found</h2>
    <p>The page you tried to view does not exist
     Try the <a href="/">home</a> page</p>
    </center>
    </body>
    </html>
      <!-- END MAIN PAGE CONTENT -->
      <!-- START BOTTOM NAV CONTENT -->
      <HR>
      <div style="margin-left: auto; margin-right:auto; width: 100%; text-align: center; ">
      &copy; 2007-2018, [e] Enphase Energy, Inc. All rights reserved. |
      <a href="http://www.enphaseenergy.com/licenses">Licenses</a>
      <!-- END BOTTOM NAV CONTENT -->
      <br><br>
      </div>
      </body>
      </html>

[1/29/2021, 3:48:09 PM] [enphaseEnvoy] Device: 192.168.2.25 Envoy-S, last inverter: undefined power: NaN W
[1/29/2021, 3:48:09 PM] [enphaseEnvoy] Device: 192.168.2.25 Envoy-S, max inverter: undefined power: NaN W
```

**Comment by hoefs** [comment]
Same html in logs with homebridge-enphase-envoy v3.5.79

**Comment by hoefs** [comment]
New update shows error:
```
USER: root
DIR: /homebridge
CMD: npm install --save homebridge-enphase-envoy@latest

npm ERR! code ETARGET
npm ERR! notarget No matching version found for http@0.0.1-secutity.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'homebridge-enphase-envoy'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-29T15_02_59_446Z-debug.log

Command failed. Please review log for details.
```

**Comment by grzegorz914** [comment]
please do not update without announcement please still on 3.5.0

**Comment by hoefs** [comment]
> please do not update without announcement please still on 3.5.0

How can I roll back? The updates just show up in homebridge GUI...

Please advise

**Comment by hoefs** [comment]
New error for homebridge-enphase-envoy v3.5.83

`[1/29/2021, 4:11:01 PM] [enphaseEnvoy] Device: 192.168.2.25 Envoy-S, could not read inverters production, error: TypeError [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. Expected "https:"`

**Comment by hoefs** [comment]
homebridge-enphase-envoy v3.5.86

[1/29/2021, 4:32:39 PM] [enphaseEnvoy] Device: 192.168.2.25 Envoy-S, could not read inverters production, error: Error: Request failed with status code 401
    at createError (/homebridge/node_modules/homebridge-enphase-envoy/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/homebridge/node_modules/homebridge-enphase-envoy/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/homebridge/node_modules/homebridge-enphase-envoy/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  config: [Object],
  request: [ClientRequest],
  response: [Object],
  isAxiosError: true,
  toJSON: [Function: toJSON]

**Comment by hoefs** [comment]
homebridge-enphase-envoy v3.5.89
```
[1/29/2021, 4:44:54 PM] [enphaseEnvoy] Device: 192.168.2.25 Envoy-S, could not read inverters production, error: Error: Request failed with status code 401
    at createError (/homebridge/node_modules/homebridge-enphase-envoy/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/homebridge/node_modules/homebridge-enphase-envoy/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/homebridge/node_modules/homebridge-enphase-envoy/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  config: [Object],
  request: [ClientRequest],
  response: [Object],
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
```

**Comment by hoefs** [comment]
homebridge-enphase-envoy v3.5.94

[1/29/2021, 5:12:23 PM] [enphaseEnvoy] Device: 192.168.2.25 Envoy-S, could not read inverters production, error: Error: Request failed with status code 401
    at createError (/homebridge/node_modules/homebridge-enphase-envoy/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/homebridge/node_modules/homebridge-enphase-envoy/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/homebridge/node_modules/homebridge-enphase-envoy/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  config: [Object],
  request: [ClientRequest],
  response: [Object],
  isAxiosError: true,
  toJSON: [Function: toJSON]

**Comment by hoefs** [comment]
homebridge-enphase-envoy v3.5.96

```
[1/29/2021, 5:24:11 PM] [enphaseEnvoy] Device: 192.168.2.25 Envoy-S, could not read inverters production, error: Error: Request failed with status code 401
    at createError (/homebridge/node_modules/homebridge-enphase-envoy/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/homebridge/node_modules/homebridge-enphase-envoy/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/homebridge/node_modules/homebridge-enphase-envoy/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  config: [Object],
  request: [ClientRequest],
  response: [Object],
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
```

**Comment by hoefs** [comment]
Same html in logs with homebridge-enphase-envoy v3.5.104

**Comment by grzegorz914** [comment]
v3.6.0 released

**Comment by hoefs** [comment]
When I try to update it wants to update to 3.6.61 beta...
